name: build

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      image: "app-test:latest"
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: build
        run: docker build -t ${{ env.image }} -f DockerfileTest .
      - name: run tests
        run: docker run --rm ${{ env.image }}
  build:
    runs-on: ubuntu-24.04
    needs: tests
    env:
      image: "app:${{ github.sha }}"
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build
        uses: docker/build-push-action@v7
        with:
          push: false
          file: Dockerfile
          context: .
          tags: ${{ env.image }}


